
# ╭────────────────────────────ImplementationGuide-hl7.org.nz.hpi.json─────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

id: hl7.org.nz.fhir.ig.nhi
canonical: http://hl7.org.nz/fhir/ig/nhi
version: 0.10.0
name: NewZealandNHIIG
title: New Zealand NHI IG
status: active
publisher:
  name: David Hay
  email: mailto:david.hay25@gmail.com
description: The FHIRb  API for the NHI
license: CC0-1.0

dependencies:
   fhir.org.nz.ig.base:
     uri: 'http://fhir.org.nz/ig/base'
     version: 1.0.0
     
   hl7.org.nz.fhir.ig.hip-core:
     #uri: 'https://nzhts.digital.health.nz/ig/hip-common-terminology'
     uri: 'https://dev.d3ox9vcqia2rpj.amplifyapp.com/site'
     version: 1.0.0
     
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: CI Build


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  API: capabilityStatement.html
  Profiles: profiles.html
  Extensions: extensions.html
  Identifiers: namingSystems.html
  Terminology: terminology.html
  Table of Contents: toc.html
  Artifact Index: artifacts.html
  Support:
    FHIR Spec: new-tab http://hl7.org/fhir/R4/index.html




