
# ╭────────────────────────────ImplementationGuide-hl7.org.nz.hpi.json─────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

id: hl7.org.nz.fhir.ig.nhi
canonical: http://hl7.org.nz/fhir/ig/nhi
version: 1.1.0 Snapshot
name: NewZealandNHIIG
title: New Zealand NHI IG
status: active
publisher:
 name: Te Whatu Ora
 email: mailto:integration@health.govt.nz
description: The FHIR  API for the NHI
license: CC0-1.0

dependencies:
   fhir.org.nz.ig.base:
     #uri: 'http://fhir.org.nz/ig/base'
     uri: 'http://build.fhir.org/ig/HL7NZ/nzbase/branches/master'
     #version: 1.0.0
     version: dev

   hl7.org.nz.fhir.ig.hip-core:
     uri: 'https://nzhts.digital.health.nz/ig/hip-common-terminology'
     #uri: 'https://dev.d3ox9vcqia2rpj.amplifyapp.com/site/ImplementationGuide/ig.hip.digital.health.nz.base'
     version: dev
     
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: Release


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Business View: businessView.html
  Use cases:
    Guidance: guidance.html
    Get patient: getPatient.html
    Match patient: matchPatient.html
    Validate patient: validatePatient.html
    Add patient: addPatient.html
    Update name: updateName.html
    Update address: updateAddress.html
  Important information:
    Onboarding and Compliance testing: OnboardingAndComplianceTesting.html
    General Notes: general.html
    FAQ: FAQ.html
  API: capabilityStatement.html
  Profiles: profiles.html
  Extensions: extensions.html
  Identifiers: namingSystems.html
  Terminology: terminology.html
  Table of Contents: toc.html
  Artifact Index: artifacts.html
  Support:
    FHIR Spec: new-tab http://hl7.org/fhir/R4/index.html
    Download IG : full-ig.zip
    Artifacts (Json): definitions.json.zip
    Artifacts (Xml): definitions.xml.zip
    "OpenApi 3 spec": NhiFhirOpenApi.zip



