# ╭────────────────────────────ImplementationGuide-hl7.org.nz.hpi.json─────────────────────────────╮

# │  The properties below are used to create the ImplementationGuide resource. For a list of       │

# │  supported properties, see:                                                                    │

# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │

# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

id: hl7.org.nz.fhir.ig.nhi
canonical: http://hl7.org.nz/fhir/ig/nhi
version: 1.4.1
name: NewZealandNHIIG
title: New Zealand NHI IG
status: active
publisher:
  name: Te Whatu Ora
  email: mailto:integration@health.govt.nz
description: The FHIR  API for the NHI
license: CC0-1.0
date: 2022-08-03
dependencies:
  #hl7.fhir.uv.extensions.r4: 
   # version: 1.0.0
  fhir.org.nz.ig.base:
    uri: 'https://fhir.org.nz/ig/base/'
    version: 2.0.0
  hl7.org.nz.fhir.ig.hip-core:
    uri: https://common-ig-v1-2-0.hip.digital.health.nz/site
    version: 1.3.1
fhirVersion: 4.0.1
parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: Release
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮

# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │

# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Business View: businessView.html
  Use cases:
    Guidance: guidance.html
    Get patient: getPatient.html
    Match patient: matchPatient.html
    Validate patient: validatePatient.html
    Create patient: createPatient.html
    Update name: updateName.html
    Update address: updateAddress.html
    Update identity: updateIdentity.html
    Update birth: updateBirth.html
    Update eligibility: updateEligibility.html
    Consumer Facing API: ConsumerFacingAPI.html
  Important information:
    Onboarding: Onboarding.html
    General Notes: general.html
    FAQ: FAQ.html
    Glossary: glossary.html
  Compliance Testing:
    Compliance testing important information: ComplianceTestingImportantInformation.html
    Get and Match Patient Compliance testing: GetAndMatchPatientComplianceTesting.html
    Update Patient Compliance testing: UpdatePatientComplianceTesting.html
    Create Patient Compliance testing: CreatePatientComplianceTesting.html
    Consumer Facing API Compliance testing: ConsumerAuthComplianceTesting.html
  API: API.html
  Profiles: profiles.html
  Extensions: extensions.html
  Identifiers: namingSystems.html
  Terminology: terminology.html
  Table of Contents: toc.html
  Artifact Index: artifacts.html
  Support:
    FHIR Spec: new-tab http://hl7.org/fhir/R4/index.html
    Download IG: full-ig.zip
    Artifacts (Json): definitions.json.zip
    Artifacts (Xml): definitions.xml.zip
    "OpenApi 3 spec": NhiFhirOpenApi.zip
