Extension: Informationsource
Id: informationsource
Description: "The source of the information"
//These files were generated by a script from a model at NzNHIPatient.dateOfDeath.source

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from http://standards.digital.health.nz/fhir/ValueSet/dodinfosource (preferred)