
Extension: Informationsource
Id: informationsource
Description: "The source of the information"
//These files were generated by a script from a model at NzNHIPatient.dateOfDeath.source
* ^url = http://hl7.org.nz/fhir/StructureDefinition/informationsource


* extension 0..0
* value[x] only CodeableConcept
//* valueCodeableConcept from https://standards.digital.health.nz/fhir/ValueSet/informationsource (preferred)

