Extension: IsPrimaryAddress
Id: isPrimaryAddress
Description: "Indicates this is the primary residential address - each patient must have one and only one"
//These files were generated by a script from a model at NzNHIPatient.address.isPrimary

* extension 0..0
* value[x] only boolean