Extension: NzEthnicity
Id: nz-ethnicity
Description: "The ethnicity of the individual. Uses level 4 codes (most detailed)."
//These files were generated by a script from a model at NzNHIPatient.ethnicity

* ^url = "http://hl7.org.nz/fhir/StructureDefinition/nz-ethnicity"
* ^jurisdiction.coding = urn:iso:std:iso:3166#NZ

* extension 0..0
* value[x] only CodeableConcept
* valueCodeableConcept from https://standards.digital.health.nz/fhir/ValueSet/ethnic-group-level-4-code (preferred)