Instance: ZAT2496
InstanceOf: Patient
Description: "Example Patient -  With linked 'dormant' identifier"
Usage: #example
* meta.versionId = "3344625"
* meta.profile = "http://hl7.org.nz/fhir/StructureDefinition/NhiPatient"
* extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-ethnicity"
* extension[=].valueCodeableConcept.coding.version = "2.0"
* extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/ethnic-group-level-4-code#51113 "Assyrian"
* extension[=].valueCodeableConcept.text = "Assyrian"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-ethnicity"
* extension[=].valueCodeableConcept.coding.version = "2.0"
* extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/ethnic-group-level-4-code#12913 "Austrian"
* extension[=].valueCodeableConcept.text = "Austrian"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/birth-place"
* extension[=].extension[0].url = "country"
* extension[=].extension[=].valueCodeableConcept.coding.version = "2013"
* extension[=].extension[=].valueCodeableConcept.coding = urn:iso:std:iso:3166#NZ "New Zealand"
* extension[=].extension[=].valueCodeableConcept.text = "New Zealand"
* extension[=].extension[+].url = "place-of-birth"
* extension[=].extension[=].valueString = "Christchurch"
* extension[=].extension[+].url = "source"
* extension[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* extension[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#BRCT "Birth Certificate"
* extension[=].extension[=].valueCodeableConcept.text = "Birth Certificate"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-citizenship"
* extension[=].extension.url = "status"
* extension[=].extension.valueCodeableConcept.coding.version = "1.0.0"
* extension[=].extension.valueCodeableConcept.coding = https://standards.digital.health.nz/ns/nz-citizenship-status-code#unknown "The citizenship status is unknown"
* extension[=].extension.valueCodeableConcept.text = "The citizenship status is unknown"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-residency"
* extension[=].extension[0].url = "source"
* extension[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* extension[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#HL7 "HL7 applied"
* extension[=].extension[=].valueCodeableConcept.text = "HL7 applied"
* extension[=].extension[+].url = "status"
* extension[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* extension[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/nz-residency-code#yes "Permanent Resident"
* extension[=].extension[=].valueCodeableConcept.text = "Permanent Resident"
* identifier[0].use = #official
* identifier[=].system = "https://standards.digital.health.nz/ns/nhi-id"
* identifier[=].value = "ZAT2496"
* identifier[=].assigner = Reference(Organization/G00001-G)
* identifier[+].use = #old
* identifier[=].system = "https://standards.digital.health.nz/ns/nhi-id"
* identifier[=].value = "ZAT2518"
* identifier[=].assigner = Reference(Organization/G00001-G)
* name[0].id = "78"
* name[=].extension.url = "http://hl7.org/fhir/StructureDefinition/iso21090-preferred"
* name[=].extension.valueBoolean = false
* name[=].family = "Moh"
* name[=].given = "Woody"
* name[+].id = "77"
* name[=].extension.url = "http://hl7.org/fhir/StructureDefinition/iso21090-preferred"
* name[=].extension.valueBoolean = true
* name[=].family = "Yossarian"
* name[=].given[0] = "John"
* name[=].given[+] = "Test"
* name[+].id = "16"
* name[=].extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/information-source"
* name[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* name[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#NPRF "Proof not Sighted"
* name[=].extension[=].valueCodeableConcept.text = "Proof not Sighted"
* name[=].extension[+].url = "http://hl7.org/fhir/StructureDefinition/iso21090-preferred"
* name[=].extension[=].valueBoolean = false
* name[=].family = "Making"
* name[=].given[0] = "Poor"
* name[=].given[+] = "Decision"
* name[=].prefix = "SIR"
* name[+].id = "15"
* name[=].extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/information-source"
* name[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* name[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#NPRF "Proof not Sighted"
* name[=].extension[=].valueCodeableConcept.text = "Proof not Sighted"
* name[=].extension[+].url = "http://hl7.org/fhir/StructureDefinition/iso21090-preferred"
* name[=].extension[=].valueBoolean = false
* name[=].family = "Rochester"
* name[=].given = "Edward  "
* gender = #male
* birthDate = "1914-01-01"
* birthDate.extension.url = "http://hl7.org.nz/fhir/StructureDefinition/information-source"
* birthDate.extension.valueCodeableConcept.coding.version = "1.0.0"
* birthDate.extension.valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#NPRF "Proof not Sighted"
* birthDate.extension.valueCodeableConcept.text = "Proof not Sighted"
* deceasedDateTime = "1976-10"
* deceasedDateTime.extension.url = "http://hl7.org.nz/fhir/StructureDefinition/information-source"
* deceasedDateTime.extension.valueCodeableConcept.coding.version = "1.0.0"
* deceasedDateTime.extension.valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#DREG "Death Register"
* deceasedDateTime.extension.valueCodeableConcept.text = "Death Register"
* address.id = "27"
* address.extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/not-validated-address-reason"
* address.extension[=].valueCodeableConcept.coding.version = "1.1"
* address.extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/address-not-validated-reason-code#OTHER "Other"
* address.extension[=].valueCodeableConcept.text = "Other"
* address.extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/domicile-code"
* address.extension[=].valueCodeableConcept = https://standards.digital.health.nz/ns/domicile-code#2125 "Willis Street-Cambridge Terrace"
* address.extension[=].valueCodeableConcept.text = "Willis Street-Cambridge Terrace"
* address.extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/suburb"
* address.extension[=].valueString = "Te Aro"
* address.use = #home
* address.type = #physical
* address.line = "Courtenay Place"
* address.city = "Wellington"
* address.postalCode = "6011"
