Instance: ZJM9397
InstanceOf: Patient
Description: "Example Patient 1"
Usage: #example
* meta.versionId = "3324612"
* meta.profile = "http://hl7.org.nz/fhir/StructureDefinition/NhiPatient"
* extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-ethnicity"
* extension[=].valueCodeableConcept.coding.version = "2.0"
* extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/ethnic-group-level-4-code#21111 "Māori"
* extension[=].valueCodeableConcept.text = "Māori"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-ethnicity"
* extension[=].valueCodeableConcept.coding.version = "2.0"
* extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/ethnic-group-level-4-code#11111 "New Zealand European"
* extension[=].valueCodeableConcept.text = "New Zealand European"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/birth-place"
* extension[=].extension[0].url = "country"
* extension[=].extension[=].valueCodeableConcept.coding.version = "2013"
* extension[=].extension[=].valueCodeableConcept.coding = urn:iso:std:iso:3166#NZ "New Zealand"
* extension[=].extension[=].valueCodeableConcept.text = "New Zealand"
* extension[=].extension[+].url = "place-of-birth"
* extension[=].extension[=].valueString = "Whangarei"
* extension[=].extension[+].url = "source"
* extension[=].extension[=].valueCodeableConcept.coding.version = "1.0"
* extension[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#BRCT "Birth Certificate"
* extension[=].extension[=].valueCodeableConcept.text = "Birth Certificate"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-citizenship"
* extension[=].extension[0].url = "source"
* extension[=].extension[=].valueCodeableConcept.coding.version = "1.0"
* extension[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#BRCT "Birth Certificate"
* extension[=].extension[=].valueCodeableConcept.text = "Birth Certificate"
* extension[=].extension[+].url = "status"
* extension[=].extension[=].valueCodeableConcept.coding.version = "1.1.0"
* extension[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/nz-citizenship-status-code#yes "yes"
* extension[=].extension[=].valueCodeableConcept.text = "yes"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/dhb"
* extension[=].valueCodeableConcept.coding.version = "1.0"
* extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/dhb-code#G00036-D "Capital & Coast"
* extension[=].valueCodeableConcept.text = "Capital & Coast"
* identifier.use = #official
* identifier.system = "https://standards.digital.health.nz/ns/nhi-id"
* identifier.value = "ZJM9397"
* identifier.assigner = Reference(Organization/G00001-G)
* name[0].extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/information-source"
* name[=].extension[=].valueCodeableConcept.coding.version = "1.0"
* name[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#NPRF "Proof not Sighted"
* name[=].extension[=].valueCodeableConcept.text = "Proof not Sighted"
* name[=].extension[+].url = "http://hl7.org/fhir/StructureDefinition/iso21090-preferred"
* name[=].extension[=].valueBoolean = true
* name[=].text = "Ryan, Jamie Joseph"
* name[=].family = "Ryan"
* name[=].given[0] = "Jamie"
* name[=].given[+] = "Joseph"
* name[=].prefix = "MR"
* name[+].extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/information-source"
* name[=].extension[=].valueCodeableConcept.coding.version = "1.0"
* name[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#NPRF "Proof not Sighted"
* name[=].extension[=].valueCodeableConcept.text = "Proof not Sighted"
* name[=].extension[+].url = "http://hl7.org/fhir/StructureDefinition/iso21090-preferred"
* name[=].extension[=].valueBoolean = false
* name[=].text = "James, Joseph Ryan"
* name[=].family = "James"
* name[=].given[0] = "Joseph"
* name[=].given[+] = "Ryan"
* name[=].prefix = "MR"
* gender = #male
* birthDate = "1972-06-05"
* birthDate.extension.url = "http://hl7.org.nz/fhir/StructureDefinition/information-source"
* birthDate.extension.valueCodeableConcept.coding.version = "1.0"
* birthDate.extension.valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#BRCT "Birth Certificate"
* birthDate.extension.valueCodeableConcept.text = "Birth Certificate"
* address.extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/is-primary-address"
* address.extension[=].valueBoolean = true
* address.extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/domicile-code"
* address.extension[=].valueCodeableConcept = https://standards.digital.health.nz/ns/domicile-code#2077 "Thorndon - Tinakori Road"
* address.extension[=].valueCodeableConcept.text = "Thorndon - Tinakori Road"
* address.extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/suburb"
* address.extension[=].valueString = "Thorndon"
* address.use = #home
* address.type = #physical
* address.line = "133 Molesworth Street"
* address.city = "Wellington"
* address.postalCode = "6011"
