Instance: ZJM9397
InstanceOf: Patient
Description: "Patient with validated residential and mailing addresses"
Usage: #example
* meta.versionId = "3368249"
* meta.profile = "http://hl7.org.nz/fhir/StructureDefinition/NhiPatient"
* extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-ethnicity"
* extension[=].valueCodeableConcept.coding.version = "2.0"
* extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/ethnic-group-level-4-code#21111 "Māori"
* extension[=].valueCodeableConcept.text = "Māori"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-ethnicity"
* extension[=].valueCodeableConcept.coding.version = "2.0"
* extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/ethnic-group-level-4-code#11111 "New Zealand European"
* extension[=].valueCodeableConcept.text = "New Zealand European"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/birth-place"
* extension[=].extension[0].url = "country"
* extension[=].extension[=].valueCodeableConcept.coding.version = "2013"
* extension[=].extension[=].valueCodeableConcept.coding = urn:iso:std:iso:3166#NZ "New Zealand"
* extension[=].extension[=].valueCodeableConcept.text = "New Zealand"
* extension[=].extension[+].url = "source"
* extension[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* extension[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#BRCT "Birth Certificate"
* extension[=].extension[=].valueCodeableConcept.text = "Birth Certificate"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-citizenship"
* extension[=].extension[0].url = "source"
* extension[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* extension[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#BRCT "Birth Certificate"
* extension[=].extension[=].valueCodeableConcept.text = "Birth Certificate"
* extension[=].extension[+].url = "status"
* extension[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* extension[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/nz-citizenship-status-code#yes "Yes"
* extension[=].extension[=].valueCodeableConcept.text = "Yes"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-residency"
* extension[=].extension[0].url = "source"
* extension[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* extension[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#MIGR "Migrated"
* extension[=].extension[=].valueCodeableConcept.text = "Migrated"
* extension[=].extension[+].url = "status"
* extension[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* extension[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/nz-residency-code#no "Not a Permanent Resident"
* extension[=].extension[=].valueCodeableConcept.text = "Not a Permanent Resident"
* extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/dhb"
* extension[=].valueCodeableConcept.coding.version = "1.0.0"
* extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/dhb-code#G00033-J "Mid Central District Health Board"
* extension[=].valueCodeableConcept.text = "Mid Central District Health Board"
* identifier.use = #official
* identifier.system = "https://standards.digital.health.nz/ns/nhi-id"
* identifier.value = "ZJM9397"
* identifier.assigner = Reference(Organization/G00001-G)
* name[0].id = "22"
* name[=].extension.url = "http://hl7.org/fhir/StructureDefinition/iso21090-preferred"
* name[=].extension.valueBoolean = false
* name[=].given = "ChewyBakA"
* name[=].prefix = "MR"
* name[+].id = "21"
* name[=].extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/information-source"
* name[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* name[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#NPRF "Proof not Sighted"
* name[=].extension[=].valueCodeableConcept.text = "Proof not Sighted"
* name[=].extension[+].url = "http://hl7.org/fhir/StructureDefinition/iso21090-preferred"
* name[=].extension[=].valueBoolean = false
* name[=].use = #nickname
* name[=].family = "Ryan"
* name[=].given = "Chewea"
* name[=].prefix = "MR"
* name[+].id = "13"
* name[=].extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/information-source"
* name[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* name[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#NPRF "Proof not Sighted"
* name[=].extension[=].valueCodeableConcept.text = "Proof not Sighted"
* name[=].extension[+].url = "http://hl7.org/fhir/StructureDefinition/iso21090-preferred"
* name[=].extension[=].valueBoolean = false
* name[=].family = "James"
* name[=].given[0] = "Joseph"
* name[=].given[+] = "Ryan"
* name[=].prefix = "MR"
* name[+].id = "11"
* name[=].extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/information-source"
* name[=].extension[=].valueCodeableConcept.coding.version = "1.0.0"
* name[=].extension[=].valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#NPRF "Proof not Sighted"
* name[=].extension[=].valueCodeableConcept.text = "Proof not Sighted"
* name[=].extension[+].url = "http://hl7.org/fhir/StructureDefinition/iso21090-preferred"
* name[=].extension[=].valueBoolean = true
* name[=].family = "Ryan"
* name[=].given[0] = "Jamie"
* name[=].given[+] = "Joseph"
* name[=].prefix = "MR"
* gender = #male
* birthDate = "1972-06-05"
* birthDate.extension.url = "http://hl7.org.nz/fhir/StructureDefinition/information-source"
* birthDate.extension.valueCodeableConcept.coding.version = "1.0.0"
* birthDate.extension.valueCodeableConcept.coding = https://standards.digital.health.nz/ns/information-source-code#HL7 "HL7 applied"
* birthDate.extension.valueCodeableConcept.text = "HL7 applied"
* address[0].id = "27"
* address[=].extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-address-id"
* address[=].extension[=].valueString = "1199146"
* address[=].extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/domicile-code"
* address[=].extension[=].valueCodeableConcept = https://standards.digital.health.nz/ns/domicile-code#1852 "Awapuni North"
* address[=].extension[=].valueCodeableConcept.text = "Awapuni North"
* address[=].extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/suburb"
* address[=].extension[=].valueString = "Awapuni"
* address[=].use = #home
* address[=].type = #physical
* address[=].line = "24 Anglesey Place"
* address[=].city = "Palmerston North"
* address[=].postalCode = "4412"
* address[=].country = "NZ"
* address[+].id = "28"
* address[=].extension[0].url = "http://hl7.org.nz/fhir/StructureDefinition/nz-address-id"
* address[=].extension[=].valueString = "6025652"
* address[=].extension[+].url = "http://hl7.org.nz/fhir/StructureDefinition/domicile-code"
* address[=].extension[=].valueCodeableConcept = https://standards.digital.health.nz/ns/domicile-code#1628 "New Plymouth Central"
* address[=].extension[=].valueCodeableConcept.text = "New Plymouth Central"
* address[=].use = #home
* address[=].type = #postal
* address[=].line = "PO Box 8255"
* address[=].city = "New Plymouth"
* address[=].postalCode = "4340"
* address[=].country = "NZ"
